### ISSUE TITLE
Raft-WSL is not properly integrated with Microsoft PowerToys

### ISSUE THREAD

**Issue by Jack31071973** [WhitewaterFoundry/Raft-WSL-Feedback#13]
PowerToys Ver: v0.47.1
Raft Ver: 21.7.4.0
OS ver: Windows 10 Pro for Workstation (Latest update).

Raft-WLS is not properly integrated with Microsoft PowerToys, please find attached file. In PowerToys Run menu, plugins Raft is not present so you cannot enable it as should be.

![BugRaft](https://user-images.githubusercontent.com/64733228/137338551-fcf1e884-f1af-4ec3-aff2-5414d36a547f.PNG)

**Comment by crramirez** [comment]
Hello @Jack31071973,

Thanks for reporting. PowerToys 0.47.0 introduced a change that made our integration approach fail. We are still working on solving it. If you want to use the integration meanwhile, please downgrade PowerToys to 0.43.0.

https://github.com/microsoft/PowerToys/releases/download/v0.45.0/PowerToysSetup-0.45.0-x64.exe

I'll post here when we have released a fix for that.

Sorry for the caused inconveniences.

Regards,
Carlos

**Comment by crramirez** [comment]
Hello,

There is a new release in the store with the fix. Check it out.

Regards,
Carlos

**Comment by Jack31071973** [comment]
Hi,
I tried the latest version of Raft-WSL, anyway the issue is still there.
PowerToys Ver: v0.49.1 (this is latest version).

**Comment by crramirez** [comment]
The latest version of Raft is 21.11.x check if you have it

**Comment by Jack31071973** [comment]
yes, I have
PowerToys Ver: v0.49.1 (this is latest version).
Raft-WLS Ver: 21.11.5.0

There is Windows terminal (as add
![PowerToysScreen](https://user-images.githubusercontent.com/64733228/140775509-2542a9ad-e836-4e7a-adcd-704e6c6e5158.PNG)
)

**Comment by crramirez** [comment]
It takes time to show the icon there. But try with Alt+Space and type $$ to see if the Raft entries appear.

**Comment by Jack31071973** [comment]
No, it does not

**Comment by crramirez** [comment]
Ok let's investigate what is happening in your case because it is not the same issue.

First question. How did you install powertoys?

**Comment by Jack31071973** [comment]
Sorry for the delay, I followed the normal installation provided by Microsoft, I used the downloaded package from Microsoft.

**Comment by crramirez** [comment]
Please confirm me the following things in order:

1. Do you have the following folder? 
`%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins\WhitewaterFoundry.Plugin.RaftWSL`
2. Be sure that PowerToys is running. Can you delete the folder `WhitewaterFoundry.Plugin.RaftWSL`? Did it give you any errors?
3. If you receive an error, exit PowerToys and try again.
4. If Raft WSL is running, close it and run it again. The folder should be filled again.
5. Open PowerToys again and invoke Alt+Space the write $$
6. Does it work?

Thanks 
Carlos

**Comment by Jack31071973** [comment]
Hi @crramirez here is the problem the WhitewaterFoundry.Plugin.RaftWSL is not present in the folder %LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins\

Tested with:
**Raft-WSL Version:** 
21.11.5.0
21.11.6.0
21.11.7.0

Other steps I did:
Close Raft-WSL and PowerToys.
Re-Start PowerToys and Raft-WSL
Checked the folder but still WhitewaterFoundry.Plugin.RaftWSL is not present.

Uninstall PowerToys and re-install it from github (Version v0.49.1 same version as before) still the problem is there.
 - Installation file from github: PowerToysSetup-0.49.1-x64.exe. After installation I checked the folder, and here the result.
![PowerToysFolders](https://user-images.githubusercontent.com/64733228/141643198-3cb018b8-59ce-4cb3-b7dc-c5d8a55b9f6d.PNG)

**Comment by Jack31071973** [comment]
Can I do something else? the issue is still present even with latest update.

**Comment by crramirez** [comment]
I am completely lost. I don't know why is not creating the folder. Could you please send me an email to: contact@whitewaterfoundry.com ?

I'll provide you the content of this folder so you can use the feature.

Regards,
Carlos

**Comment by Jack31071973** [comment]
Hi Carlos,
Of course I can send you the email, and here we are:
- ***@***.******@***.***>

Anyway for me it is not a big issues, I do not care to much, the main point for me it was to discover why it does not create this folder, and avoid this issue for others too.
If you have any other steps to test, that we can try it (such as remove everything and re-install power toys and raft reset or re-install or check permission folder) .


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by crramirez** [comment]
Hello @Jack31071973,

I am releasing a new version that better tracks errors in the plugin installation. I'll tell you when it is available.

Regards,
Carlos

**Comment by crramirez** [comment]
Hello @Jack31071973,

Do the following steps:

1. Enable the **Command output window**:
![image](https://user-images.githubusercontent.com/8397379/144633312-33cda7a9-060c-4850-a544-132a12860ebc.png)
2. Click the expand button:
![image](https://user-images.githubusercontent.com/8397379/144633389-19de7612-74bb-4669-8189-4716779ed838.png)
3. Restart Raft WSL
4. Look for an error message below "Checking if the PowerToys plugin is installed, and try to install it."
![image](https://user-images.githubusercontent.com/8397379/144633542-780e5d03-0500-4162-b3f9-c7887d7048d6.png)

And tell me if it says something

**Comment by Jack31071973** [comment]
Hi @Carlos Rafael ***@***.***>

I check it, and noting strange appear, I mean it is checking for “PowerToys is installed and try to install  it” . Please find attached image.

Regards
Giacomo

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by Jack31071973** [comment]
Hi @crramirez 
here the attached image.
![Raft_WSL_PT_issue](https://user-images.githubusercontent.com/64733228/144643116-dfd33fab-600a-4e66-86d1-b08b3a23fc58.PNG)

**Comment by crramirez** [comment]
Ok it is not a bad permissions error. 😭

Well, I'll check again the code to see if I can add more log entries

**Comment by crramirez** [comment]
The other option is that, Raft is creating it but in another place. Can you make a full search of "WhitewaterFoundry.Plugin.RaftWSL" in your home directory? %USERPROFILE%

**Comment by Jack31071973** [comment]
No,

there isn’t such file in my home directory sorry!!!

Regards
Giacomo

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Jack31071973** [comment]
Can I try to reset or repair the Raft-WLS application from windows?

**Comment by Jack31071973** [comment]
@crramirez did you mean this file, please find attached image?
 WhitewaterFoundry.Plugin.RaftWSL.dll
![RaftLocationFiles](https://user-images.githubusercontent.com/64733228/144651629-de0a4660-0b1f-4902-a8ff-be8de599e1b3.PNG)

**Comment by crramirez** [comment]
This file is one that needs to be copied to the right folder. Your are seeing the Raft WSL installatiom folder

**Comment by Jack31071973** [comment]
Ok @crramirez what I need to do copy this file in the correct folder (I am a Linux user)?

**Comment by crramirez** [comment]
Copy the folder that contains this file into %LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins this is essentially what Raft should be doing automatically.

**Comment by Jack31071973** [comment]
Hi @crramirez thanks a lot for the help, now the integration between PowerToys and Raft-WLS works as expected. I do not know if this issue can be general or related to my OS configuration, and so I will close it as resolved (fill free to reopen it).

**Comment by crramirez** [comment]
You are very welcome and thanks for the collaboration. I still wanted to know why it is not being copied automatically. And I am afraid that other users can have the same problem.

**Comment by Jack31071973** [comment]
Ok, let me know if I can do something when you are ready. I can remove the folder I copied and see if it is recreated automatically. This is my OS info, basically Windows Pro + some features.

Edition	Windows 10 Pro for Workstations
Version	21H1
Installed on	‎6/‎14/‎2020
OS build	19043.1387
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by Jack31071973** [comment]
Hi @crramirez I still have this problem in my side, which seems affect just me. Anyway, it could be possible the WhitewaterFoundry.Plugin.RaftWSL will not be copied because Microsoft PowerToys is running. I mean, I tried to copy the file in the correct folder, as workaround you suggest (it works), but to be able to copy and paste I need to close Microsoft PowerToys, otherwise you can't. In my case PowerToys by default run on startup (option in PowerToys).

**Comment by crramirez** [comment]
Hello @Jack31071973,

Upon Raft seeing that if it cannot copy the file it shows this:

![image](https://user-images.githubusercontent.com/8397379/159790339-07cf81aa-bcc4-4aff-90ad-4a5ccc8c9dc8.png)

So, for me, the problem in your case is I still figure that Raft is copying the files in the wrong folder

**Comment by Jack31071973** [comment]
Ok @crramirez, I get where is the problem, the message is not showing up in my case. If I make the same procedure manually:
- Install the latest version of PowerToys and close it. Close Raft-WSL.
- run Raft-WSL
- run PowerToys
At this point everything is working fine, the file is copied, and the integration works as expected. My guess is there is some problem with the **box-message "Power Toys plugin upgrade"** because it is not show up as expected.

**Comment by crramirez** [comment]
Hmm, the message box is shown when Raft tries to copy the DLL and Windows returns an error message. Let's see if there is another flow that can make it silently fail.

But happy that you could find a workaround

**Comment by Jack31071973** [comment]
Hello,
Ok I never see that message in my case. The only think, I can do is try to remove power toys and install it from Microsoft App Store, close raft and restart the laptop, and then try to run raft and powertoys again.

Anyway, my powertoys is always running so when I update the raft Plugin no message showed up as supposed to be, strange.

Thanks
Giacomo

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
